#!/bin/sh /etc/rc.common

START=99
STOP=01

pidfile=/var/run/dfs_check

start() {
  echo start dfs_check
  echo "*/15 * * * * sh /etc/dfs_check.sh" >> /etc/crontabs/root
  /etc/init.d/cron restart
}
stop() {
  echo stop dfs_check
  sed -i "/dfs_check.sh/d" /etc/crontabs/root
  /etc/init.d/cron restart
}
